// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://biqgqcwxtparahedgnes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpcWdxY3d4dHBhcmFoZWRnbmVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MTUyNDksImV4cCI6MjA2MzI5MTI0OX0.QrMmoUwFf4ZOulYJDQ2uH0oG0_2Oq7HNcZvoLduCzJs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);